import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import HomeProfile from "./components/home";
import LoginBtn from "./components/loginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="nav-bar">
          <Link href='/' className="home">Home</Link>
          <Link href='/list'>list</Link>
          <Link href='/write'>write</Link>
          <LoginBtn login={session}/>
        </div>
        <div className="home-container">
          <div className="children">{children}</div>
          <div className="home-profile"><HomeProfile login={session}/></div>
        </div>
        </body>
    </html>
  );
}
